# Generated by Django 5.0.4 on 2024-06-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Sent'), (1, 'Delivered'), (2, 'Read')])),
                ('time', models.DateTimeField()),
                ('description', models.TextField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='events.event')),
            ],
        ),
    ]
