[tool.ruff]
line-length = 120

[tool.ruff.lint.per-file-ignores]
"src/system/settings/*" = ["F403"]

[tool.ruff.format]
quote-style = "single"

[tool.isort]
line_length = 120
lines_after_imports = 2
sections = [
    "FUTURE",
    "STDLIB",
    "FRAMEWORK",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
default_section = "THIRDPARTY"
known_framework = "django, rest_framework"
known_first_party = "applications"
skip="*/migrations/"