# Generated by Django 5.0.4 on 2024-04-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typed_events', to='events.eventtype'),
        ),
    ]
