# Generated by Django 5.0.4 on 2024-05-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_alter_event_type'),
        ('events', '0003_eventcomment'),
    ]

    operations = [
    ]
