# Generated by Django 5.0.4 on 2024-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_author_alter_event_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reference_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
