# Generated by Django 5.0.4 on 2024-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
